version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: conviver
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  api:
    build: ./conViver.API
    depends_on:
      - postgres
      - redis
    environment:
      DB_CONNECTION: Host=postgres;Port=5432;Username=postgres;Password=devpass;Database=conviver;
      REDIS_CONNECTION: redis:6379
      JWT_SECRET: dev-secret
    ports:
      - "5000:80"
