// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using conViver.Infrastructure.Data.Contexts;

#nullable disable

namespace conViver.Infrastructure.Migrations
{
    [DbContext(typeof(ConViverDbContext))]
    partial class ConViverDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("conViver.Core.Entities.AvaliacaoPrestador", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Comentario")
                    .HasColumnType("TEXT");

                b.Property<Guid>("CondominioId")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DataAvaliacao")
                    .HasColumnType("TEXT");

                b.Property<int>("Nota")
                    .HasColumnType("INTEGER");

                b.Property<Guid?>("OrdemServicoId")
                    .HasColumnType("TEXT");

                b.Property<Guid>("PrestadorServicoId")
                    .HasColumnType("TEXT");

                b.Property<Guid>("UsuarioId")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("PrestadorServicoId", "UsuarioId", "OrdemServicoId");

                b.ToTable("AvaliacoesPrestadores");
            });

            modelBuilder.Entity("conViver.Core.Entities.Aviso", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Categoria")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<Guid>("CondominioId")
                    .HasColumnType("TEXT");

                b.Property<string>("Corpo")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("PublicadoEm")
                    .HasColumnType("TEXT");

                b.Property<Guid?>("PublicadoPor")
                    .HasColumnType("TEXT");

                b.Property<string>("Titulo")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Avisos");
            });

            modelBuilder.Entity("conViver.Core.Entities.Boleto", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("CodigoBanco")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("DataEnvio")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("DataPagamento")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("DataRegistro")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DataVencimento")
                    .HasColumnType("TEXT");

                b.Property<string>("LinhaDigitavel")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("NossoNumero")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.Property<Guid>("UnidadeId")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<decimal>("Valor")
                    .HasColumnType("TEXT");

                b.Property<decimal?>("ValorPago")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("NossoNumero", "CodigoBanco")
                    .IsUnique();

                b.ToTable("Boletos");
            });

            modelBuilder.Entity("conViver.Core.Entities.Chamado", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("AvaliacaoComentario")
                    .HasColumnType("TEXT");

                b.Property<int?>("AvaliacaoNota")
                    .HasColumnType("INTEGER");

                b.Property<Guid>("CondominioId")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DataAbertura")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("DataResolucao")
                    .HasColumnType("TEXT");

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Fotos")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("RespostaDoSindico")
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Titulo")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<Guid?>("UnidadeId")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<Guid>("UsuarioId")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Chamados");
            });

            modelBuilder.Entity("conViver.Core.Entities.Condominio", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<bool>("Ativo")
                    .HasColumnType("INTEGER");

                b.Property<string>("Cnpj")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Condominios");
            });

            modelBuilder.Entity("conViver.Core.Entities.Documento", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Categoria")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<Guid>("CondominioId")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DataUpload")
                    .HasColumnType("TEXT");

                b.Property<string>("NomeArquivoOriginal")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<long>("TamanhoArquivoBytes")
                    .HasColumnType("INTEGER");

                b.Property<string>("TipoArquivo")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("TituloDescritivo")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Url")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<Guid>("UsuarioUploadId")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Documentos");
            });

            modelBuilder.Entity("conViver.Core.Entities.Encomenda", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("CodigoRastreio")
                    .HasColumnType("TEXT");

                b.Property<string>("CodigoRetirada")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DataStatus")
                    .HasColumnType("TEXT");

                b.Property<string>("Descricao")
                    .HasColumnType("TEXT");

                b.Property<string>("FotoUrl")
                    .HasColumnType("TEXT");

                b.Property<string>("Observacoes")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("RecebidoEm")
                    .HasColumnType("TEXT");

                b.Property<Guid?>("RecebidoPor")
                    .HasColumnType("TEXT");

                b.Property<string>("Remetente")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("RetiradoEm")
                    .HasColumnType("TEXT");

                b.Property<Guid?>("RetiradoPor")
                    .HasColumnType("TEXT");

                b.Property<string>("RetiradoPorTerceiroDocumento")
                    .HasColumnType("TEXT");

                b.Property<string>("RetiradoPorTerceiroNome")
                    .HasColumnType("TEXT");

                b.Property<int>("Status")
                    .HasColumnType("INTEGER");

                b.Property<Guid>("UnidadeId")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Encomendas");
            });

            modelBuilder.Entity("conViver.Core.Entities.LancamentoFinanceiro", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("Data")
                    .HasColumnType("TEXT");

                b.Property<string>("Descricao")
                    .HasColumnType("TEXT");

                b.Property<string>("Tipo")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<Guid>("UnidadeId")
                    .HasColumnType("TEXT");

                b.Property<decimal>("Valor")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Lancamentos");
            });

            // Resolved Ocorrencia section:
            modelBuilder.Entity("conViver.Core.Entities.Ocorrencia", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Titulo")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Categoria")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Prioridade")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DataAbertura")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DataAtualizacao")
                    .HasColumnType("TEXT");

                b.Property<Guid>("UsuarioId")
                    .HasColumnType("TEXT");

                b.Property<Guid?>("UnidadeId")
                    .HasColumnType("TEXT");

                b.Property<Guid>("CondominioId")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("CondominioId");
                b.HasIndex("UnidadeId");
                b.HasIndex("UsuarioId");

                b.ToTable("Ocorrencias");
            });

            modelBuilder.Entity("conViver.Core.Entities.OcorrenciaAnexo", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("NomeArquivo")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Tipo")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<long>("Tamanho")
                    .HasColumnType("INTEGER");

                b.Property<string>("Url")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<Guid>("OcorrenciaId")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("OcorrenciaId");

                b.ToTable("OcorrenciaAnexos");
            });

            modelBuilder.Entity("conViver.Core.Entities.OcorrenciaComentario", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Texto")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("Data")
                    .HasColumnType("TEXT");

                b.Property<Guid>("OcorrenciaId")
                    .HasColumnType("TEXT");

                b.Property<Guid>("UsuarioId")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("OcorrenciaId");
                b.HasIndex("UsuarioId");

                b.ToTable("OcorrenciaComentarios");
            });

            modelBuilder.Entity("conViver.Core.Entities.OcorrenciaStatusHistorico", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("Data")
                    .HasColumnType("TEXT");

                b.Property<Guid>("OcorrenciaId")
                    .HasColumnType("TEXT");

                b.Property<Guid>("AlteradoPorId")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("OcorrenciaId");
                b.HasIndex("AlteradoPorId");

                b.ToTable("OcorrenciaStatusHistoricos");
            });

            // ... (rest of entities unchanged)
#pragma warning restore 612, 618
        }
    }
}
