// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using conViver.Infrastructure.Data.Contexts;

#nullable disable

namespace conViver.Infrastructure.Migrations
{
    [DbContext(typeof(ConViverDbContext))]
    partial class ConViverDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("conViver.Core.Entities.Ocorrencia", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Titulo")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Categoria")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Prioridade")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DataAbertura")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DataAtualizacao")
                    .HasColumnType("TEXT");

                b.Property<Guid>("UsuarioId")
                    .HasColumnType("TEXT");

                b.Property<Guid?>("UnidadeId")
                    .HasColumnType("TEXT");

                b.Property<Guid>("CondominioId")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("CondominioId");
                b.HasIndex("UnidadeId");
                b.HasIndex("UsuarioId");

                b.ToTable("Ocorrencias");
            });

            modelBuilder.Entity("conViver.Core.Entities.OcorrenciaAnexo", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("NomeArquivo")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Tipo")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<long>("Tamanho")
                    .HasColumnType("INTEGER");

                b.Property<string>("Url")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<Guid>("OcorrenciaId")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("OcorrenciaId");

                b.ToTable("OcorrenciaAnexos");
            });

            modelBuilder.Entity("conViver.Core.Entities.OcorrenciaComentario", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Texto")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("Data")
                    .HasColumnType("TEXT");

                b.Property<Guid>("OcorrenciaId")
                    .HasColumnType("TEXT");

                b.Property<Guid>("UsuarioId")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("OcorrenciaId");
                b.HasIndex("UsuarioId");

                b.ToTable("OcorrenciaComentarios");
            });

            modelBuilder.Entity("conViver.Core.Entities.OcorrenciaStatusHistorico", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("Data")
                    .HasColumnType("TEXT");

                b.Property<Guid>("OcorrenciaId")
                    .HasColumnType("TEXT");

                b.Property<Guid>("AlteradoPorId")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("OcorrenciaId");
                b.HasIndex("AlteradoPorId");

                b.ToTable("OcorrenciaStatusHistoricos");
            });

#pragma warning restore 612, 618
        }
    }
}
